---
- name: Copy cloudflare config
  copy:
    src: files/etc/apache2/conf-available/cf.conf
    dest: /etc/apache2/conf-available/cf.conf
    mode: '0600'
  notify: restart apache2

- name: Enable configurations
  file:
    src: /etc/apache2/conf-available/{{ item }}.conf
    dest: /etc/apache2/conf-enabled/{{ item }}.conf
    state: link
  loop:
    - cf
